### ISSUE TITLE
Add send meal+bolus possibility to Meal view?

### ISSUE THREAD

**Issue by dsnallfot** [dsnallfot/LoopFollowiAPS#26]
Idea to enable an even smoother workflow
when registering remote meals:

Edit: Added checkboxes for what I’ve testing so far in mealbolus branch 

**Basic functionality**
- [x] Add possibility to send meal+bolus together from Meal view

- [x] Add maxBolus (and maxCarbs)guardrails

- [x] Add faceID/TouchID/Passcode for additional confirmation/security before sending meal+bolus

- [x] Add "Bolus_x.x" to Meal text string (to use in if-statement in sms triggered automation shortcut on receiving phone)

**Bolus calculator/recommendations**
- [ ] Use enacted device status data to fetch CR (to use for "naive" bolus calculation of a suggested bolus amount)

- [ ] Use lowest BG prediction value (and/or insulinreq) from enacted and suggest 0 bolus if prediction is lower than threshold 

- [ ] Use enacted device status data to show latest IOB, COB, Eventual BG (as additional info for an informed bolus decision) This could maybe be displayed in the navigation bar?

**Other**
- [x] Make bolus functionality optional with toggle show/hide in settings (default hide)

- [x] Change text on send button to “send meal+bolus” when bolus entry is made, or just “send meal” when bolus is 0 or “”

- [x] Guardrail alerts: Show maxbolus alert (stop sending) if maxbolus is exceeded, otherwise continue, then check that maxcarbs is not exceeded, if exceeded, show maxcarbs alert and stop sending, otherwise continue sending

**Comment by dsnallfot** [comment]
Some screenshots from a testing branch (work in progress and sorry for some Swedish text). 

Yes, this is working right now (but the bolus amount is not yet connected to any CR or other calculations. Just maxBolus guardrai)l. And FaceID gets enabled as a second confirmation step if any bolus amount larger than 0 is entered and send button is clicked (otherwise, when only sending carbs, only one confirmation yes/cancel is shown)

| Dark mode | Light mode | Max Bolus exceeded | Max Carbs exceeded  |
|--------|--------|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-03-26 at 22 18 58](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/88048dc5-deaa-474f-b6fd-ad8d8307b87d) | ![Simulator Screenshot - iPhone 13 - 2024-03-26 at 22 19 07](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/2db0b576-3032-4926-91c1-8d449268edac) | ![Simulator Screenshot - iPhone 13 - 2024-03-26 at 22 19 38](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/b0646903-8059-4939-a59f-d30eb349759e) | ![Simulator Screenshot - iPhone 13 - 2024-03-26 at 22 19 53](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/413147fb-4351-4ba7-b6f8-e78b02c24b34) |

| Confirmation without bolus | Confirmation with bolus step 1  | Confirmation with bolus step 2 | Textstring generated |
|--------|--------|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-03-26 at 22 19 30](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/7edccdb9-8a84-4c6c-96d1-59f3e56ccbbc) | ![Simulator Screenshot - iPhone 13 - 2024-03-26 at 22 19 19](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/46a7984a-e7f1-41f0-a534-61b22bb9842f) | ![Simulator Screenshot - iPhone 13 - 2024-03-26 at 22 20 29](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/9f199d1e-e122-4d3c-b881-5527261b16fd) | ![Simulator Screenshot - iPhone 13 - 2024-03-26 at 22 20 45](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/9adae403-fae2-46d6-82d4-982833289c46) |

**Comment by dsnallfot** [comment]
| Send button when no Bolus is entered | Send button when bolus is entered |
|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 00 16 48](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/7ab647d9-065f-4ff7-894e-9ce205f2ac5b) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 00 16 44](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/460c950e-b6ad-4ef8-83d1-b396265145d5) | 

Swedish "Skicka Måltid och Bolus" = "Send Meal and Bolus"

**Comment by dsnallfot** [comment]
| Remote view Bolus visible | Bolus hidden | Meal view bolus visible | Bolus hidden | Hide setting |
|--------|--------|--------|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 01 53 29](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/7179b59b-acc0-43fc-bc18-40bd5182c098) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 01 57 20](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/a7217799-1cf3-4e5b-8b50-165b0ab21e27) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 01 53 34](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/2e5ae0a7-ff8c-42f4-aa63-e9b8e4587fc0) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 01 57 26](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/a897c144-087c-4d9c-a041-626c3bfd6f89) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 01 57 48](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/c3708bd2-337d-4369-ae06-9192688c0038) | 

Need to figure out a way to show/hide bolus button in Remote Main View without force closing/restarting the app (to reload and read the latest on/off setting to memory).

**Comment by dsnallfot** [comment]
Slightly unrelated, but I will also make the custom action button possible to show/hide in settings in the same manner

**Comment by dsnallfot** [comment]
Hide custom actions switch added. 

Below are all possible combinations of buttons on the remote main screen. Bolus and custom actions ("Förval" in this Swedish version) shows/hides with switches in settings

| All buttons | Hide custom | Hide bolus | Hide custom & bolus |
|--------|--------|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 09 44 58](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/75ea2499-a465-41a9-9c1d-de29395e5876) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 09 41 03](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/301686cd-719d-4253-abaa-1a81e8f3969e) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 09 44 05](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/2924b870-f32c-4588-85e6-36f162de28cb) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 09 38 39](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/e77f0d3c-98c1-428a-8cc0-c1cd05f0772f) | 


Settings

| Hide custom | Hide bolus | Hide custom & bolus |
|--------|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 09 40 20](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/bf48d056-f0c9-40aa-96c2-7646a4417e2a) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 09 40 33](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/1e9595a8-8c07-42c8-bade-01e310eba0fe) | ![Simulator Screenshot - iPhone 13 - 2024-03-27 at 09 40 39](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/185ce860-802f-48c9-9723-98813778e5b3) |

**Comment by aug0211** [comment]
Love these - my intuition would be to "flip" these show/hide toggles for the advanced functions. The reasoning here is I would think of the advanced features being "off" or "disabled" by default. I'd have the switches match that, to show "off" as the default state, and require the user to enable them by flipping them "on" or "enabled".

This would mean renaming the switches to something like "Show Bolus Actions" and "Show Custom Actions" and having them set to off by default.

Curious for your thoughts on this.

**Comment by dsnallfot** [comment]
I totally agree on the intuition logic. The only reason "hide" is on is that I did not want to reverse all code since it's used in several places. But that is something we should do. agree

**Comment by dsnallfot** [comment]
> Love these - my intuition would be to "flip" these show/hide toggles for the advanced functions. The reasoning here is I would think of the advanced features being "off" or "disabled" by default. I'd have the switches match that, to show "off" as the default state, and require the user to enable them by flipping them "on" or "enabled".
> 
> This would mean renaming the switches to something like "Show Bolus Actions" and "Show Custom Actions" and having them set to off by default.
> 
> Curious for your thoughts on this.

Buttons fixed in PR #41 now. 😊

**Comment by dsnallfot** [comment]
CLosing this since bolus now is implemented in meal view.

Create new issue for the Bolus Calculator stuff (could be a big undertaking and maybe not in scope in the near future)
