### ISSUE TITLE
Produce user guides for shortcuts/Twilio setup?

### ISSUE THREAD

**Issue by dsnallfot** [dsnallfot/LoopFollowiAPS#28]
Remote functionality in LF requires lots of quite advanced automations/iOS shortcuts configuration on both sending and receiving phones (regex decoding of text strings and if-logic on the receiving phone primarily).

If this functionality is to be released for the wider user base we really need to produce some sort of guides on how to create relevant automations and shortcuts, and where to find credentials for the Twilio service and how to configure LF with this. 

An alternative is that we only target advanced users and keep all things remote toggled off as default and possible to activate in advanced settings if the user is willing to do all configuration needed for it. 

The major argument for keeping this for advanced users is that the targeted user base is followers using an APS app other than Loop (where Loop Caregiver is an existing and much more viable solution for the everyday user with less need of configurations). 

All remote development has been done with iAPS in mind (and as a solution to the limitations of iAPS current Nightscout integration for anything remote related)

**Comment by aug0211** [comment]
We should definitely do this.

One interesting way of doing this could be by tapping into the iAPS community and finding another technical/advanced Caregiver who is also willing/able/experienced in writing documentation to do this with us, while they set this up for themselves.

My thinking here is that it will help get a new user on board, get someone who is less familiar with what we did to poke holes in things we might take for granted, and help our early adopter/documentation writer to onboard to become a semi-expert very quickly.
