### ISSUE TITLE
Create UI view for remote commands triggers

### ISSUE THREAD

**Issue by dsnallfot** [dsnallfot/LoopFollowiAPS#3]
Prepare UI view with triggers such as buttons, text/numbers input etc that is to be used for iAPS remote control. 

It should be set up to be
- Accessible form home screen, in tab bar or with separate button.

It should be designed to work with:
- Preferred solution: Third part sms relay service API integration, and/or
- Hack solution: Trigger local iPhone shortcuts

Other considerations:
- One single view for everything, or several linked navigation views/popups/sheets/modals for different treatments (Meal, Bolus, Overrides, Temp Targets, Other)?

**Comment by aug0211** [comment]
- Started with a tab view approach
- 3 buttons added (meal, bolus, override)
- Bolus screen implementation started
- No logic for sending commands yet
- https://github.com/dsnallfot/LoopFollowiAPS/pull/5

**Comment by dsnallfot** [comment]
- Temp target button added in Remote view
- Remote meal view added
- No logic for sending commands yet
- https://github.com/dsnallfot/LoopFollowiAPS/pull/7

**Comment by dsnallfot** [comment]
This part of the work is now done and UI MVP (with lot of goodies) is in place after PR #10 

CLosing this issue, and work continues with the more hardcode code implementation of sms API solution (and refinement of the UI MVP)
