### ISSUE TITLE
Rename "Custom Presets" in code

### ISSUE THREAD

**Issue by aug0211** [dsnallfot/LoopFollowiAPS#34]
Rename Custom Presets in code to match the "Custom Actions" shown in the UI
This improves code readability because the code variables match the buttons in the interface
This also avoids confusion with a future (different issue) addition to bring Custom Temp Targets (have seen people - including myself! - mix up terms between "presets" and "overrides" and "temp targets")

**Comment by dsnallfot** [comment]
Good point. Code started out as Meal Presets and became Custom Actions/Presets on the way. Needs to be cleaned up

**Comment by dsnallfot** [comment]
Working on this. Will PR rename of all things "preset" to "Custom Action" soon

**Comment by dsnallfot** [comment]
Fixed in PR #48
