### ISSUE TITLE
Add a "Custom Temp Target" to temp targets screen

### ISSUE THREAD

**Issue by aug0211** [dsnallfot/LoopFollowiAPS#35]
Allow users to enter a custom duration and a custom target in the temp target screen
Perhaps add an option to the school wheel called "Custom" and when it is highlighted, magically show Duration and Target fields the user can tap and enter into to set (and hide these fields when a different temp target is selected)

**Comment by dsnallfot** [comment]
This is a great idea, but I think we need to build this with a NS API call since current  iAPS shortcuts implementation only can trigger preset Temp Targets by name on the receiving phone (to my knowledge) and not customized entries?

**Comment by aug0211** [comment]
Let's not do this now. Good for the future backlog, but should not be a priority for our v1.
