### ISSUE TITLE
"Healthlog" button appears to be hard coded to a shortcut, not 100% sure what this button does

### ISSUE THREAD

**Issue by aug0211** [dsnallfot/LoopFollowiAPS#36]
This button appears to launch a shortcut called "Healthlog". I do not have this shortcut on my device, I am guessing it is something like logging an entry in Apple Health.

Perhaps when the user selects "SMS API" instead of "Shortcuts", this button should be used to add a note to NS?

**Comment by dsnallfot** [comment]
Ah, that was not supposed to be part of the PR to dev-remote (from my special branch where we use that shortcut for all NS logging). We can remove the button or make the link customizable if we want to keep it

**Comment by dsnallfot** [comment]
Found another thing that shouldn't be in the PR to Dev Remote but was included by mistake, its my custom coloring of the low-in range-high buttons in main vc. 
<img width="399" alt="Skärmavbild 2024-03-28 kl  23 20 29" src="https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/a04399a9-dcf8-4614-ab19-79ad3bb7cf88">

**Comment by dsnallfot** [comment]
new issue #59 on todo list
