### ISSUE TITLE
Allow emoji entries in food notes

### ISSUE THREAD

**Issue by aug0211** [dsnallfot/LoopFollowiAPS#37]
Allow emojis such as 🌮🍕🍭 and so forth to be entered in the meal notes tab - do this by updating the keyboard type to allow this (I think).

**Comment by dsnallfot** [comment]
This should already be implemented or did I miss that in the PR to dev remote maybe?
Keyboard type default
![Simulator Screenshot - iPhone 13 - 2024-03-28 at 23 10 20](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/c56fba68-ac1a-4f01-b3dd-02c2ac0b9ea2)

**Comment by aug0211** [comment]
I think this is good! I must have looked at an old version by accident. I just double checked and I see what you see!

**Comment by aug0211** [comment]
I think this is good! I must have looked at an old version by accident. I just double checked and I see what you see!
