### ISSUE TITLE
Force close due to null LoopStatusLabel

### ISSUE THREAD

**Issue by aug0211** [dsnallfot/LoopFollowiAPS#46]
- Saw this bug in the passed, my old fix worked but not sure why I fixed the way I did
- We should look into the starting point of our fork and see how it originally was set up and revert to this (somehow it changed in a decent PR I suspect)
- Workaround right now is to disable pulling in Loop data
- Line 302 of DeviceStatus

**Comment by aug0211** [comment]
Old fix from my personal repo - probably had more going on here, just adding for reference. ![image](https://github.com/dsnallfot/LoopFollowiAPS/assets/659845/9bdb80c9-092a-458d-ad0e-02bddf3b5372)

**Comment by aug0211** [comment]
It's odd that I don't see a recent PR (last ~2 weeks) that modified this file.

**Comment by aug0211** [comment]
There are 0 changes to this file in our fork. I don't think we've modified anything that would interact with device status data in this fork, either.

It's unclear to me whether this is actually a new issue we introduced somehow - not sure why it just started showing up in the most recent build and deploy I did today (a recent build from sometime earlier this week seems to be running fine with the same NS info on the same device).

![image](https://github.com/dsnallfot/LoopFollowiAPS/assets/659845/ba0f86a6-4205-4abc-9a2f-c63bacf0bd73)

**Comment by aug0211** [comment]
@dsnallfot do you encounter this issue at all, maybe if you use a fresh bundle ID to test with for a net new install?

I cannot trace back to why this is showing up for me all of a suddent.

Looks like I had this issue in the past to, because in my fork I had commented out the offending line - did not even use a proper fix because I think this logic was ultimately not needed for me.

The challenge is, I don't want to change this in our fork unless it's truly required as a fix (in which case it should probably go to main rather than our fork anyway).

**Comment by dsnallfot** [comment]
@aug0211 Let me check. Didn't you hide/delete the loop label on the main screen in your branch?.. I have a vague memory that I had to do something with the loop label text when I did the same thing  (to make room for COB, UAM, IOB, ZT labels with the prediction number) Will check if I can find this

**Comment by dsnallfot** [comment]
clue 1: I think im on to something.. the label you commented out is an @IBOutlet weak var LoopStatusLabel: UILabel! in MainViewController..

**Comment by dsnallfot** [comment]
So the breaking change is probably not in deviceStatus, my bet is that its in main.storyboard.

Can you tell me exact which branch you're seeing this in? is it in Dev Remote? Edit: Obviously it is. Tested myself and connected to NS and encountered the same error

**Comment by dsnallfot** [comment]
Yes, now I see and understand what this is all about. Built dev-remote.

its the loop statuslabel that's missing from main-storyboard that. This must have happened at the same time when a couple of other customizations from my special branch found its way into dev-remote after a bad merge (together with the red-green-yellow stats labels). The quick fix is to comment out 4 of those from loopstatus. The proper fix is to restore the label in main storyboard.
<img width="1043" alt="Skärmavbild 2024-03-29 kl  23 53 47" src="https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/26b60b95-0525-4609-acb2-dd3b77e9d1ad">

**Comment by dsnallfot** [comment]
i have this commented out in my special branch like above (since I removed the loop status symbol from main storyboard). That was not supposed to be the case in dev-remote.

**Comment by dsnallfot** [comment]
Should now be fixed with PR #58
