### ISSUE TITLE
Button colors in remote views?

### ISSUE THREAD

**Issue by dsnallfot** [dsnallfot/LoopFollowiAPS#67]
I have implemented this button UI modifications in my personal special branch, is this something we want in our dev-remote branch?

The send buttons are the same colors as the colors in remote main view to give a quick visual clue on what remote view you're currently at

| Custom Actions | Meal | Bolus | Override | Temp Target |
|--------|--------|--------|--------|--------|
| ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 07 54](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/47a12827-4327-47a1-82f6-f1daf13cfdd1) | ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 07 58](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/459e8bbc-6969-4df3-bd79-2223b4418882) | ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 08 02](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/a5948852-3445-43ef-bfa2-ae98508b60fb) | ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 08 05](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/94f7c107-7589-4df5-adf5-7dc0279144bc) | ![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 08 09](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/e4db8ff4-b373-4493-89d4-171c17775592) |

**The same colors on each button in remote view**

![Simulator Screenshot - iPhone 13 - 2024-04-15 at 12 07 51](https://github.com/dsnallfot/LoopFollowiAPS/assets/72826201/1b63dd3e-cbcb-44d4-967a-2ca36e22f0c4)

**Comment by aug0211** [comment]
I say ship it. Diabetes needs some fun sometimes, and these buttons add just that.

Plus, they provide a functional design purpose like you mentioned - a low touch cognitive reminder of the type of function you're working with. This is a very small thing, but from a safety perspective, it's actually quite nice to "build a brand" around a certain type of function (override, bolus, meal, etc) for general quick recall and identification of "oops, wrong screen, don't press anything!" moments.

**Comment by dsnallfot** [comment]
Great! I put this on my "to make a PR of shortly"-list

**Comment by dsnallfot** [comment]
Added in PR #69 
Closing this issue
